#!/bin/sh
rootdir=$(pwd)
init=true
binutils=true
gcc1=true
linux_headers=true
glibc_headers=true
libgcc=true
glibc_libc_so=true
gcc_cpp=true

if [ "$prefix" = "" ]; then
	prefix=$(echo ~/cross)
fi

# init
if [ $init = true ]; then
	./get-deps && cd tarballs && ../decompress-all
	for i in $(ls | grep -v .tar); do
		mv $i ..
	done
fi

# binutils
if [ $binutils = true ]; then
	cd binutils-2.38
	mkdir -p build
	cd build
	../configure --prefix=$prefix --target=i686-pocket-linux-musl --disable-mutilib
	make -j2
	make install
	cd $rootdir
fi

# gcc c/c++ compilers
if [ $gcc1 = true ]; then
	ln $rootdir/gmp-6.2.1 gcc-11.2.0/gmp -s
	ln $rootdir/mpc-1.2.1 gcc-11.2.0/mpc -s
	ln $rootdir/mpfr-4.1.0 gcc-11.2.0/mpfr -s

	cd gcc-11.2.0
	mkdir -p build
	cd build
	../configure --prefix=$prefix --target=i686-pocket-linux-musl --disable-multilib --enable-languages=c,c++
	make -j2 all-gcc
	make install-gcc
	cd $rootdir
fi

# linux headers
if [ $linux_headers = true ]; then
	cd linux-5.16.10
	make INSTALL_HDR_PATH=$prefix/i686-pocket-linux-musl headers_install
	cd $rootdir
fi

# glibc header files
if [ $glibc_headers = true ]; then
	cd musl-1.2.2
	../configure --prefix=$prefix/i686-pocket-linux-musl --target=i686-pocket-linux-musl --disable-multilib
	make install
	cd $rootdir
fi

# gcc support lib
if [ $libgcc = true ]; then
	cd gcc-11.2.0/build
	make -j2 all-target-libgcc
	make install-target-libgcc
	cd $rootdir
fi

# glibc libc.so
if [ $glibc_libc_so = true ]; then
	cd musl-1.2.2
	make -j2
	make install
	cd $rootdir
fi

# gcc c++ library
if [ $gcc_cpp = true ]; then
	cd gcc-11.2.0/build
	make -j2
	make install
	cd $rootdir
fi
