#!/usr/bin/env ruby
# SPDX-License-Identifier: MPL-2.0

require 'yaml'

def parseArgs
	args = ARGV

	while args.length > 0
		case args[0]
			when "-h"
				puts "Usage: #{$0} [-b build|-c lvl|-hc|-h] {-t threads}"
				puts " -b	Builds a component"
				puts "		Valid options:"
				puts "			toolchain"
				puts "			rootfs"
				puts "			boot-img"
				puts "			kernel"
				puts " -t	Sets the amount of threads to use in compilation"
				puts "		Default: all threads when ran on a system under 4 threads, half of all threads otherwise"
				puts " -c	Cleans the build directory at the specified level of cleaning"
				puts "		Valid options:"
				puts "			1 (bare minimum)"
				puts "			2 (default, deletes internal build dir for autoconf projects)"
				puts "			3 (stronger, deletes output directory)"
				puts "			4 (hard clean, deletes all directories and files generated by the configure and build process)"
				puts " -hc	Equivalent to -c 4"
				puts " -h	Shows this help"
				puts "For more information, please go to https://github.com/pocketlinux32/portalinux"
				exit
			else
				errorHandler("Unknown option", true)
		end
		args.shift
	end
end

def init
	if File.exist?(".config") == false
		puts "Error: No configuration found. Please run ./configure.rb -h for more information"
		exit 1
	end

	parsedConfig = YAML.load_file(".config")
	case parsedConfig["toolchain"]
		when "llvm"
			puts "Launching LLVM target..."
		when "gcc"
			puts "Launching GCC target"
		else
			puts "Error: Invalid configure file"
			exit 1
	end
end

puts "PortaLinux Build System v0.11"
puts "(c) 2022-2023 pocketlinux32 & raisinware, Under MPL 2.0"
