#!/bin/sh
device_list="$(blkid -s TYPE)"
end_loop=""

main_prog(){
	printf "* Looking for devices..."
	if [ "$device_list" = "" ]; then
		echo "No devices found"
		echo "* Cancelling automount..."
	else
		echo "Found devices"
		for device in $(echo $device_list | cut -d: -f1); do
			filesystem="$(echo $device_list | grep $device | cut -d\" -f2)"
			if [ "$filesystem" != "" ]; then
				printf "* Mounting $device ($filesystem)..."
				if [ ! -d "/mnt/$(basename $device)" ]; then
					mkdir "/mnt/$(basename $device)"
					mount "$device" -t "$filesystem" -o ro "/mnt/$(basename $device)"
					echo "Done."
					break
				else
					echo "Already Mounted."
				fi
			fi
		done
	fi

	for folder in $(ls /mnt); do
		if [ $(ls /dev | grep -c "$folder") -eq 0 ]; then
			rmdir /mnt/$folder 2>/dev/null
		fi
	done
}

while [ "$end_loop" = "" ]; do
	main_prog
	sleep 1
	if [ "$1" != "" ]; then
		end_loop="end"
	fi
done
