#!/usr/bin/sh

if [ "$1" = "tb" ]; then
	toybox dmesg -n 1

	cmdList="$(toybox)"
	for i in $cmdList; do
		if [ "$i" != "sh" ] || [ "$i" != "ls" ]; then
			toybox ln -s /usr/bin/toybox /usr/bin/$i 2>/dev/null
			printf "* Creating link: $i        \\r"
		fi
	done

	echo "* Created all links        "
	echo "* Initialization done"
	exit 0
else
	source "/usr/lib/os-release"
	issue_text="$(cat /etc/issue | sed s/IMGVER/$IMAGE_VERSION/g | sed s/CURYEAR/$(date +%Y)/g)"
	printf "$issue_text\n"
	exec /bin/sh
fi
