#!/bin/sh
# PortaLinux Persistence Setup v0.01
# (c) 2024 CinnamonWolfy, Under MPL 2.0

raw_disklist="$(blkid -s TYPE)"
selected_disk=""
diskfs=""
get_disk_fs(){
	diskfs="$(echo $raw_disklist | grep $1 | cut -d\" -f2)"
}

select_disk(){
	echo "Here are all available disks:"
	disks=$(echo $raw_disklist | cut -d: -f1 | sort)
	entry_num=1
	for disk in $disks; do
		get_disk_fs $disk
		echo "$entry_num) $disk ($diskfs)"
		entry_num=$(expr $entry_num + 1)
	done
	read -p "Select a drive (number or exact string):" disksel
	if [ "$(echo $disksel | grep -o -e '^[0-9]*$')" != ""  ] && [ "$(echo $disks | sed -n '$disksel p')" != "" ]; then
		selected_disk="$(echo $disks | sed -n '$disksel p')"
		get_disk_fs $selected_disk
		echo "Selected disk $selected_disk ($diskfs)"
	elif [ $(echo "$disks" | grep "$disksel" -c) -eq 1 ]; then
		selected_disk="$(echo $disks | grep $disksel)"
		get_disk_fs $selected_disk
		echo "Selected disk $selected_disk ($diskfs)"
	else
		echo "Error: Invalid disk. Exiting..."
		exit
	fi
}

initialize_disk(){
	if [ ! -d "/mnt/$(basename $selected_disk)" ] || [ "$(mountpoint /mnt/$(basename && echo $?)" = "" ]; then
		mkdir "/mnt/$(basename $selected_disk)" -p
		mount $selected_disk -t $diskfs -o rw "/mnt/$(basename $selected_disk)"
	else
		mount -o remount,rw $selected_disk "/mnt/$(basename $selected_disk)"
	fi

	if [ "$diskfs" = "vfat" ]; then
		dd if=/dev/zero of=/mnt/$(basename $selected_disk)/persist.img bs=1M count=256
		mke2fs -j /mnt/$(basename $selected_disk)/persist.img
		mount /mnt/$(basename $selected_disk)/persist.img /opt
		echo "opt_mountpoint=persist.img" > /mnt/$(basename $selected_disk)/.pl-persist
	elif [ "$(echo $diskfs | grep ext)" != "" ]; then
		mount --bind /mnt/$(basename $selected_disk) /opt
		echo "opt_mountpoint=." > /mnt/$(basename $selected_disk)/.pl-persist
	fi

	mkdir /opt/data/home/root -p
	cp /usr/etc /opt/data -r
	cp /var /opt/data -r

	echo "Persistence drive complete"
}

if [ "$(mountpoint /opt && echo $?)" = "" ]; then
	read -p "No persistence volume mounted. Set up and enable persistence? [N/y]" yn
	if [ "$yn" = "y" ] || [ "$yn" = "Y" ]; then
		select_disk
		initialize_disk
	fi
fi
