#!/bin/sh
# PortaLinux Persistence Setup v0.01
# (c) 2024 CinnamonWolfy, Under MPL 2.0

raw_disklist="$(blkid -s TYPE | sort)"
disklist=""
selected_disk=""
selected_disk_fs=""

parse_raw_disklist(){
	for entry_chunk in $raw_disklist; do
		if [ "$disklist" = "" ]; then
			disklist="$(echo $entry_chunk | cut -d: -f1)"
		elif [ "$(echo $entry_chunk | grep TYPE)" != "" ]; then
			disklist="$disklist|$(echo $entry_chunk | cut -d'\"' -f2)"
		else
			disklist="$disklist $(echo $entry_chunk | cut -d: -f1)"
		fi
	done
}

select_disk(){
	echo "Here are all available disks:"
	parse_raw_disklist
	entry_num=1
	for disk_entry in $disklist; do
		disk=$(echo $disk_entry | cut -d'|' -f1)
		diskfs=$(echo $disk_entry | cut -d'|' -f2)
		echo "$entry_num) $disk ($diskfs)"
		entry_num=$(expr $entry_num + 1)
	done
	read -p "Select a drive (number or exact string):" disksel
	if [ "$(echo $disksel | grep -o -e '^[0-9]*$')" != ""  ] && [ "$(echo $disklist | cut -d' ' -f$disksel)" != "" ]; then
		selected_disk="$(echo $disklist | cut -d'|' -f1)"
		selected_disk_fs="$(echo $disklist | cut -d'|' -f2)"
		echo "Selected disk $selected_disk ($selected_disk_fs)"
	elif [ $(echo "$disklist" | grep "$disksel" -c) -eq 1 ]; then
		selected_disk="$disksel"
		selected_disk_fs="$(echo $disklist | grep -o $disksel|.[a-z]*)"
		echo "Selected disk $selected_disk ($selected_disk_fs)"
	else
		echo "Error: Invalid disk. Exiting..."
		exit
	fi
}

initialize_disk(){
	if [ ! -d "/mnt/$(basename $selected_disk)" ] || [ "$(mountpoint /mnt/$(basename $selected_disk) && echo $?)" = "" ]; then
		mkdir "/mnt/$(basename $selected_disk)" -p
		mount $selected_disk -t $selected_disk_fs -o rw "/mnt/$(basename $selected_disk)"
	else
		mount -o remount,rw $selected_disk "/mnt/$(basename $selected_disk)"
	fi

	if [ "$selected_disk_fs" = "vfat" ]; then
		dd if=/dev/zero of=/mnt/$(basename $selected_disk)/persist.img bs=1M count=256
		mke2fs -j /mnt/$(basename $selected_disk)/persist.img
		mount /mnt/$(basename $selected_disk)/persist.img /opt
		echo "opt_mountpoint=persist.img" > /mnt/$(basename $selected_disk)/.pl-persist
	elif [ "$(echo $selected_disk_fs | grep ext)" != "" ]; then
		umount /mnt/$(basename $selected_disk)
		mount $selected_disk /opt
		echo "opt_mountpoint=." > /mnt/$(basename $selected_disk)/.pl-persist
	fi

	mkdir /opt/data/home/root -p
	cp /usr/etc /opt/data -r
	cp /var /opt/data -r

	echo "Persistence drive complete"
}

if [ "$(mountpoint /opt > /dev/null && echo $?)" = "" ]; then
	read -p "No persistence volume mounted. Set up and enable persistence? [N/y]" yn
	if [ "$yn" = "y" ] || [ "$yn" = "Y" ]; then
		select_disk
		initialize_disk
	fi
fi
