#!/usr/bin/sh
toybox dmesg -n 1

cmdList="$(toybox)"
for i in $cmdList; do
	if [ "$i" != "sh" ] || [ "$i" != "ls" ]; then
		toybox ln -s /usr/bin/toybox /usr/bin/$i 2>/dev/null
		printf "* Creating link: $i        \\r"
	fi
done

echo "* Created all links        "
automount no-silent
enable-persistence
if [ -f "/etc/keymaps/defkmap.kmap" ]; then
	printf "* Applying custom default keymap..."
	plkeyb defkmap.kmap
	echo "Done."
fi
echo "* Initialization done"
exit 0
