#!/bin/sh
set -e
pldb_path="/var/pl-install"

verify_pkg(){
	if [ "$(echo $(basename $1) | rev | cut -d. -f1 | rev)" != "plpak" ]; then
		echo "Error: File $(basename $1) is not a valid PortaLinux package"
		exit 5
	fi

	if [ ! -f "$1" ]; then
		echo "Error: Package $(basename $1) does not exist"
		exit 2
	fi

	untar_dir=$(mktemp -d /tmp/plinstall-XXXXXX)
	absolute_pkg_path=$(realpath "$1")

	cd $untar_dir
	printf "Unpacking file $(basename $absolute_pkg_path)..."
	bzcat "$absolute_pkg_path" | tar -xf -
	echo "Done."

	pkg_name=$(cat pkg_info | sed '1q;d')
	pkg_ver=$(cat pkg_info | sed '2q;d')

	if [ -f "$pldb_path/$pkg_name.pldb" ] | [ $(cat "$pldb_path/$pkg_name.pldb" | sed '2q;d') = "$pkg_ver" ]; then
		echo "Error: Package $pkg_name is already installed"
		exit 3
	fi

	set +e
	printf "Verifying package integrity..."
	sha256sum files.tar.sha256sum 2>&1 >/dev/null
	if [ $? ]; then
		printf "Error!\nError: Package $1 does not match the hash"
		exit 6
	fi
	set -e
}

install_pkg(){
	verify_pkg "$1"

	cd $untar_dir/files
	cd ..

	if [ -f ./install.sh ]; then
		echo "Executing install script..."
		. ./install.sh $untar_dir
	else
		printf "Installing files..."
		file_list=$(find . -type f)
		cp -r ./files/* /
		echo "Done."
		echo "$file_list" >> $pldb_dir/$pkg_name.pldb
	fi

	if [ -f ./post-install.sh ]; then
		echo "Executing post-install script..."
		. ./post-install.sh $untar_dir
	fi

	if [ -f ./uninstall.sh ]; then
		mv ./uninstall.sh "$pldb_dir/$pkg_name-uninstall.sh"
	fi
}

uninstall_pkg(){
	cd /
	if [ ! -f "$pldb_dir/$1.pldb" ]; then
		echo "Error: Package $1 is not installed"
		exit 2
	fi

	if [ -f "$pldb_dir/$1-uninstall.sh" ]; then
		echo "Running uninstall script..."
		. $pldb_dir/$1-uninstall.sh
	else
		printf "Removing files..."
		for i in $(cat $pldb_dir/$1.pldb); do
			rm "$(realpath $i)"
			printf "."
		done
		echo "Done."
	fi
}

echo "PortaLinux Package Installer v0.02"
printf "(c) 2022 pocketlinux32, Under GPLv2+\n\n"

if [ $(id -u) -ne 0 ]; then
	echo "Error: You're not root"
	exit 4
fi

case $1 in
	"--install" | "install")
		install_pkg $2
		;;
	"--remove" | "--uninstall" | "remove")
		uninstall_pkg $2
		;;
	"--help" | "help")
		printf "Usage: $0 {--install|--remove} pkg_name\n\n"
		echo "--install		Installs a package"
		echo "--remove		Removes an installed package"
		echo "--help			Shows this help"
		;;
	*)
		echo "Error: Unknown option. Run $0 --help for more information"
		exit 1
		;;
esac
exit 0
