#!/bin/sh
pldb_path="/var/pl-install"

verify_pkg(){
	if [ ! -f "$1" ]; then
		echo "Error: Package $(basename $1) does not exist"
		exit 2
	fi

	untar_dir=$(mktemp -d /tmp/plinstall-XXXXXX)
	absolute_pkg_path=$(realpath "$1")

	cd $untar_dir
	printf "Unpacking file $(basename $absolute_pkg_path)..."
	bzcat "$absolute_pkg_path" 2>dev/null | tar -xf - 2>/dev/null

	if [ $? -ne 0 ] || [ ! -f files.tar ] || [ ! -f pkg_info ]; then
		printf "Error!\nError: File $(basename $1) is not a valid PortaLinux package\n"
		exit 5
	fi
	echo "Done."

	pkg_name=$(cat pkg_info | sed '1q;d')
	pkg_ver=$(cat pkg_info | sed '2q;d')

	if [ -f "$pldb_path/$pkg_name.pldb" ] && [ $(cat $pldb_path/$pkg_name.pldb | sed '2q;d') = "$pkg_ver" ]; then
		echo "Error: Package $pkg_name is already installed"
		exit 3
	fi

	set +e
	if [ ! -f files.tar.sha256sum ]; then
		local yn
		echo "Warning: Checksum not found. Cannot verify package integrity"
		read -N 1 -p "Still install package? [N/y]: " yn
		printf '\n'
		if [ "$yn" != "y" ]; then
			echo "Install aborted."
			exit 7
		fi
	else
		printf "Verifying package integrity..."
		sha256sum -c files.tar.sha256sum 2>&1 >/dev/null
		if [ $? -ne 0 ]; then
			printf "Error!\nError: Package $1 does not match the hash\n"
			exit 6
		fi
		echo "Passed!"
	fi
	set -e
}

install_pkg(){
	verify_pkg "$1"

	printf "Unpacking package..."
	tar -xf files.tar
	echo "Done"

	cd $untar_dir/files
	cd ..

	if [ -f ./install.sh ]; then
		echo "Executing install script..."
		. ./install.sh $untar_dir
	else
		printf "Installing files..."
		file_list=$(cd files && find . -type f)
		cp -r ./files/* /
		echo "Done."
		mv pkg_info "$pldb_path/$pkg_name.pldb"
		echo "$file_list" >> "$pldb_path/$pkg_name.pldb"
	fi

	if [ -f ./post-install.sh ]; then
		echo "Executing post-install script..."
		. ./post-install.sh $untar_dir
	fi

	if [ -f ./uninstall.sh ]; then
		mv ./uninstall.sh "$pldb_path/$pkg_name-uninstall.sh"
	fi
}

uninstall_pkg(){
	cd /
	if [ ! -f "$pldb_path/$1.pldb" ]; then
		echo "Error: Package $1 is not installed"
		exit 2
	fi

	if [ -f "$pldb_path/$1-uninstall.sh" ]; then
		echo "Running uninstall script..."
		. $pldb_path/$1-uninstall.sh
	else
		printf "Removing files..."
		for i in $(cat $pldb_path/$1.pldb); do
			rm "$(realpath $i)"
			printf "."
		done
		echo "Done."
	fi
}

echo "PortaLinux Package Installer v0.02"
printf "(c) 2022 pocketlinux32, Under GPLv2+\n\n"

if [ $(id -u) -ne 0 ]; then
	echo "Error: You're not root"
	exit 4
fi

if [ ! -d "$pldb_path" ]; then
	mkdir -p "$pldb_path"
fi

case $1 in
	"--install" | "install")
		install_pkg $2
		;;
	"--remove" | "--uninstall" | "remove")
		uninstall_pkg $2
		;;
	"--help" | "help")
		printf "Usage: $0 {--install|--remove} pkg_name\n\n"
		echo "--install		Installs a package"
		echo "--remove		Removes an installed package"
		echo "--help			Shows this help"
		;;
	*)
		echo "Error: Unknown option. Run $0 --help for more information"
		exit 1
		;;
esac
exit 0
