#!/usr/bin/sh
toybox dmesg -n 1

cmdList="$(toybox)"
for i in $cmdList; do
	if [ "$i" != "sh" ]; then
		toybox ln -s /usr/bin/toybox /usr/bin/$i
		echo "	* Created link $i"
	fi
done

echo "* Initialization done"
exit 0
