#!/bin/sh
device=""
devscan_timeout=10

parse_kcmdline(){
	cmdline=$(cat /proc/cmdline | egrep -o 'plflags.[a-z,0-9,\:,\,]*' | cut -d'=' -f2)

	if [ $(echo $cmdline | grep -c nodevscan) -ne 0 ]; then
		devscan_timeout=0
	elif [ $(echo $cmdline | grep -c dstimeout) -ne 0 ]; then
		devscan_timeout=$(echo $cmdline | egrep -o 'dstimeout.[0-9,\:]*' | cut -d: -f2)
		if [ "$devscan_timeout" = "" ]; then
			devscan_timeout=10
		fi
	fi

	if [ $(echo $cmdline | grep -c optdev) -ne 0 ]; then
		devscan_timeout=0
		device=$(echo $cmdline | egrep -o 'optdev.[a-z,0-9,\:]*' | cut -d: -f2)
	fi
}

device_scan(){
	for junk in $(seq 1 $devscan_timeout); do
		printf "."
		devices=$(blkid | cut -d: -f1 | grep -v loop | grep -v ram)
		for i in $devices; do
			if [ $(blkid | grep $i | grep -c ext) -ne 0 ]; then
				mount $i /opt

				if [ -f /opt/.pl-opt-mount ]; then
					device="$i"
					break
				fi

				umount /opt
			fi
		done

		if [ "$device" = "" ]; then
			sleep 1
		else
			echo "Found persistent partition at $device."
			break
		fi
	done

	if ! mountpoint /opt &>/dev/null; then
		echo "None found"
	fi
}

echo "Welcome to PortaLinux v0.08, (c) 2022 pocketlinux32 & raisinware"
printf "Init script. Running on Linux $(uname -m) $(uname -r)\n\n"

printf '#!/bin/sh\n\ngetty $@\nclear\n' > /bin/agetty
chmod 777 /bin/agetty

if [ -r /lib/modules ]; then
	printf "Loading kernel modules..."
	modprobe -a
	echo "Done."
fi

printf "Parsing command-line options..."
parse_kcmdline
echo "Done."

if [ $devscan_timeout -gt 0 ]; then
	printf "Scanning for persistent partition (/opt)..."
	device_scan
else
	echo "Device scan skipped."
	if [ "$device" != "" ] && [ -r "$device" ]; then
		mount "$device" /opt 2>/dev/null
	fi
fi

if ! mountpoint /opt &>/dev/null; then
	echo "/opt is not a mountpoint. Running without filesystem persistence."
else
	printf "Setting up filesystem persistence..."
	first_time=0

	if [ ! -r /opt/data/var ]; then
		mkdir /opt/data -p
		for i in etc home var; do
			if [ ! -d /opt/data/$i ]; then
				cp -r /$i /opt/data
			fi
		done
		first_time=1
	fi

	mount --bind /opt/data/etc /etc
	mount --bind /opt/data/home /home
	mount --bind /opt/data/var /var
	echo "Done."

	if [ $first_time -eq 1 ]; then
		echo "It seems this is the first time PortaLinux is ran with this persistence storage device."

		while [ "$ans" = "" ]; do
			read -p "Would you like to set up your system? [y/n]: " -n 1 ans
			printf "\n"
			if [ "$ans" != y ] && [ "$ans" != n ]; then
				echo "Invalid response!"
				ans=""
			fi
		done

		/bin/pl-setup
	fi
fi

if [ -d /usr/share/preinstall ]; then
	echo "Preinstalled packages detected. Installing..."
	for i in $(ls /usr/share/preinstall); do
		printf "	$i..."
		pl-install install $i >/dev/null
		echo "Done."
	done
fi
