#!/bin/sh
/bin/busybox --install -s
dmesg -n 1

echo "Welcome to PortaLinux IMG_VER, (c) 2022 pocketlinux32 & raisinware"
printf "Pre-Init. Running on Linux $(uname -m) $(uname -r)\\n\\n"

printf "Mounting pseudo-filesystems..."
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
echo "Done."

if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
	echo "Running in chroot. Aborting boot and dropping to shell..."
	/bin/sh
	for i in dev proc sys; do
		umount /$i
	done
	exit
fi

printf "Creating device nodes..."
if [ -r /proc/sys/kernel/hotplug ]; then
	echo mdev -s > /proc/sys/kernel/hotplug
else
	mdev -s
fi

printf '#!/bin/sh\\n\\ngetty $@\\nclear\\n' > /bin/agetty
chmod 777 /bin/agetty

printf "Done.\\nExecuting init...\\n\\n"
exec /sbin/init
