#!/bin/sh
/bin/busybox --install -s
dmesg -n 1

echo "Welcome to PortaLinux v0.06, (c) 2022 pocketlinux32"
printf "Pre-Init. Running on Linux $(uname -m) $(uname -r)\n\n"

if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
	echo "Running in chroot. Aborting boot and dropping to shell..."
	/bin/ash
	for i in dev proc sys; do
		umount /$i
	done
	exit
fi

printf "Mounting pseudo-filesystems..."
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
printf "Done.\nCreating device nodes..."
echo mdev -s > /proc/sys/kernel/hotplug
printf "Done.\nSwitching from ramfs to tmpfs"
mkdir -p /pivot/dev /pivot/sys /pivot/proc
for i in dev sys proc; do
	mount -o move /$i /pivot/$i
	rm -rf $i
done
for i in $(ls | grep -v init | grep -v linuxrc); do
	mv $i /pivot
done
printf "Done.\nExecuting init...\n"
exec switch_root /pivot /sbin/init
echo
