#!/bin/sh
set -e
pldb_path="/var/pl-install"

#verify_pkg(){}

install_pkg(){
	if [ "$(echo $(basename $1) | grep -xe '[A-Z,a-z,0-9]*.plpak')" = "" ]; then
		echo "Error: File $(basename $1) is not a valid PortaLinux package"
		exit 1
	fi

	pkg_name=$(basename "$1" | cut -d. -f1)

	if [ ! -f "$1" ]; then
		echo "Error: Package $pkg_name does not exist"
		exit 2
	elif [ -f "$pldb_path/$pkg_name" ]; then
		echo "Error: Package $pkg_name has already been installed"
		exit 3
	fi

	untar_dir=$(mktemp -d /tmp/plinstall-XXXXXX)
	absolute_pkg_path=$(realpath "$1")

	cd $untar_dir
	printf "Unpacking package $(basename $absolute_pkg_path)..."
	xzcat "$absolute_pkg_path" | tar -xf -
	echo "Done."

	cd files
	file_list=$(find . -type f)
	cd ..

	if [ -f ./install.sh ]; then
		echo "Executing install script..."
		./install.sh $untar_dir
	else
		printf "Installing files..."
		cp -r ./files/* /
		echo "Done."
	fi

	if [ -f ./post-install.sh ]; then
		echo "Executing post-install script..."
		./post-install.sh $untar_dir
	fi

	echo "$file_list" > /var/pl-install/$pkg_name.pldb
	if [ -f ./uninstall.sh ]; then
		mv ./uninstall.sh "/var/pl-install/$pkg_name-uninstall.sh"
	fi
}

uninstall_pkg(){
	cd /
	if [ ! -f "/var/pl-install/$1.pldb" ]; then
		echo "Error: Package $1 is not installed"
		exit 2
	fi

	if [ -f "/var/pl-install/$1-uninstall.sh" ]; then
		echo "Running uninstall script..."
		/var/pl-install/$1-uninstall.sh
	else
		printf "Removing files..."
		for i in $(cat /var/pl-install/$1.pldb); do
			rm "$(realpath $i)"
			printf "."
		done
		echo "Done."
	fi
}

echo "PortaLinux Package Installer v0.01"
printf "(c) 2022 pocketlinux32, Under GPLv2+\n\n"

case $1 in
	"--install" | "install")
		install_pkg $2
		;;
	"--remove" | "--uninstall" | "remove")
		uninstall_pkg $2
		;;
	"--help" | "help")
		printf "Usage: $0 {--install|--remove} pkg_name\n\n"
		echo "--install		Installs a package"
		echo "--remove		Removes an installed package"
		echo "--help			Shows this help"
		;;
	*)
		echo "Error: Unknown option. Run $0 --help for more information"
		exit 1
		;;
esac
exit 0
